/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.*;
import java.sql.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Tela extends javax.swing.JFrame {
    
    JDBCBancoDAO dao;
    /**
     * Creates new form Tela
     */
    public Tela() throws SQLException, ClassNotFoundException {
        initComponents();
        dao = new JDBCBancoDAO();
        abas.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numConta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numSenha = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonSaldo = new javax.swing.JButton();
        jButtonExtrato = new javax.swing.JButton();
        jButtonSaque = new javax.swing.JButton();
        jButtonDeposito = new javax.swing.JButton();
        jButtonTransferencia = new javax.swing.JButton();
        jButtonTUsuario = new javax.swing.JButton();
        jButtonSVGerente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nº da conta");

        jLabel2.setText("Senha");

        numSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSenhaActionPerformed(evt);
            }
        });

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEntrar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(numConta)
                        .addComponent(jLabel2)
                        .addComponent(numSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEntrar)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        abas.addTab("Login", jPanel1);

        jButtonSaldo.setText("Ver Saldo");
        jButtonSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaldoActionPerformed(evt);
            }
        });

        jButtonExtrato.setText("Ver Extrato");
        jButtonExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtratoActionPerformed(evt);
            }
        });

        jButtonSaque.setText("Sacar");
        jButtonSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaqueActionPerformed(evt);
            }
        });

        jButtonDeposito.setText("Depositar");
        jButtonDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositoActionPerformed(evt);
            }
        });

        jButtonTransferencia.setText("Transferir");

        jButtonTUsuario.setText("Trocar Usuário");
        jButtonTUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTUsuarioActionPerformed(evt);
            }
        });

        jButtonSVGerente.setText("Solicitar visita do Gerente");
        jButtonSVGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSVGerenteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Escolha sua opção:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSVGerente)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTransferencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExtrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTUsuario)))
                    .addComponent(jLabel4))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaldo)
                    .addComponent(jButtonExtrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaque)
                    .addComponent(jButtonDeposito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTransferencia)
                    .addComponent(jButtonTUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSVGerente)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        abas.addTab("Menu", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSenhaActionPerformed

    }//GEN-LAST:event_numSenhaActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        
        try {
            String conta = numConta.getText();
            String senha = numSenha.getText();            
            
            Correntista campos = dao.login(conta, senha);
            
            
            if( campos != null &&
                conta.equals(campos.getConta()) &&
                senha.equals(campos.getSenha())){
                
                abas.setEnabledAt(1, true);
                abas.setSelectedIndex(1);
                abas.setEnabledAt(0, false);
            }else{
                JOptionPane.showMessageDialog(this, "Nº da Conta e/ou senha inválidos");
            }
            
            String perfil = dao.Usuario();
            
            if(perfil.equals("Normal")){
                jButtonSVGerente.setEnabled(false);
            }else{
                jButtonSVGerente.setEnabled(true);
            }
            
        }catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
        }   
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonTUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTUsuarioActionPerformed
        abas.setEnabledAt(0, true);
        abas.setSelectedIndex(0);
        abas.setEnabledAt(1, false);
        
        numConta.setText("");
        numSenha.setText("");
    }//GEN-LAST:event_jButtonTUsuarioActionPerformed

    private void jButtonSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaldoActionPerformed
        
        try {
                float vSaldo = dao.verSaldo();
                JOptionPane.showMessageDialog(this, "Seu saldo é R$"+vSaldo);  
        }catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
        }
        
    }//GEN-LAST:event_jButtonSaldoActionPerformed

    private void jButtonSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaqueActionPerformed
        
        try {
            float valorReq = Float.parseFloat(JOptionPane.showInputDialog(this, "Digite o valor do saque."));
            float vSaldo = dao.verSaldo();
            float newSaldo = dao.verSaldo();
            String situacao = "saque";
            String perfil = dao.Usuario();
            
            if(valorReq != 0){
                if(perfil.equals("Vip")){
                    if(vSaldo<valorReq){
                        newSaldo-=(valorReq*(0.01*valorReq/100));
                }else{
                        newSaldo-=valorReq;
                        JOptionPane.showMessageDialog(this, "Saque realizado com sucesso!");
                    }
            } if(perfil.equals("Normal")){
                if(vSaldo<valorReq){
                    JOptionPane.showMessageDialog(this, "Saldo insulficiente!");
                }else{
                        newSaldo-=valorReq;
                        JOptionPane.showMessageDialog(this, "Saque realizado com sucesso!");
                    }
            }
                
            dao.Saque(newSaldo);
            
            Transacao transacao = new Transacao();
            transacao.setConta(dao.Usuario2());
            transacao.setDataHora(new Date(transacao.getDataHora().getTime()));
            transacao.setTipo(situacao);
            transacao.setValor(valorReq);
            
            dao.salvaTransacao(transacao);
            }else{
                JOptionPane.showMessageDialog(this, "Digite algum valor!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
    }//GEN-LAST:event_jButtonSaqueActionPerformed

    private void jButtonDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositoActionPerformed
        
        
        try {
            float valorReq = Float.parseFloat(JOptionPane.showInputDialog(this, "Digite o valor do deposito."));
            float vSaldo = dao.verSaldo();
            float newSaldo = valorReq + vSaldo;
            String situacao = "deposito";
            dao.Deposito(newSaldo);
            JOptionPane.showMessageDialog(this, "Deposito realizado com sucesso!");
            
            Transacao transacao = new Transacao();
            transacao.setConta(dao.Usuario2());
            transacao.setDataHora(new Date(transacao.getDataHora().getTime()));
            transacao.setTipo(situacao);
            transacao.setValor(valorReq);
            
            dao.salvaTransacao(transacao);
            
        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtonDepositoActionPerformed

    private void jButtonSVGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSVGerenteActionPerformed
        
        try {
            JOptionPane.showMessageDialog(this, "Gerente foi acionado para a visita.");
            float vSaldo = dao.verSaldo();
            float newSaldo = vSaldo-50;
            String situacao = "TaxaVisita";
            
            dao.solGerente(newSaldo);
            
            Transacao transacao = new Transacao();
            transacao.setConta(dao.Usuario2());
            transacao.setDataHora(new Date(transacao.getDataHora().getTime()));
            transacao.setTipo(situacao);
            transacao.setValor(50);
            
            dao.salvaTransacao(transacao);
            
        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSVGerenteActionPerformed

    private void jButtonExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExtratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton jButtonDeposito;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonExtrato;
    private javax.swing.JButton jButtonSVGerente;
    private javax.swing.JButton jButtonSaldo;
    private javax.swing.JButton jButtonSaque;
    private javax.swing.JButton jButtonTUsuario;
    private javax.swing.JButton jButtonTransferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField numConta;
    private javax.swing.JPasswordField numSenha;
    // End of variables declaration//GEN-END:variables
}